sh build.sh lstime
sh build.sh lsexception
sh build.sh lsrandom
sh build.sh lsorderedmap
sh build.sh lsbuffer
sh build.sh lscstring
sh build.sh lsio
sh build.sh lspool
sh build.sh lsalgorithm
sh build.sh lsitem
sh build.sh lscopyableitem
sh build.sh lsjson
sh build.sh lsfile
sh build.sh lsconfig
sh build.sh lslogger
sh build.sh lsepoll
sh build.sh lsnet
sh build.sh lshttp
sh build.sh lsrpc
sh build.sh lshttpprotocol
